---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext481
  labels:
    app: BoundedContext481
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext481
  template:
    metadata:
      labels:
        app: BoundedContext481
    spec:
      containers:
        - name: BoundedContext481
          image: username/BoundedContext481:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext829
  labels:
    app: BoundedContext829
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext829
  template:
    metadata:
      labels:
        app: BoundedContext829
    spec:
      containers:
        - name: BoundedContext829
          image: username/BoundedContext829:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext481
  labels:
    app: BoundedContext481
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext481


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext829
  labels:
    app: BoundedContext829
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext829

